[package]
name = "rust-web-server"
version = "0.1.0"
authors = ["Eric Lemieux <eric@lemieuxdev.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.21"
strum_macros = "0.21"
